name: widgets_demo
description: "Espace de présentation des Widgets du Design System Septeo."
publish_to: 'none'
version: 0.1.1+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  widgetbook: ^3.10.2
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  url_launcher_web: ^2.4.0
  flutter_markdown: ^0.7.6+1
  intl: ^0.19.0
  septeo_design_system:
    path: ../
  widgetbook_annotation: ^3.2.0
  flutter_resizable_container: ^3.0.4
  flutter_animate: ^4.5.2
  flutter_highlighter: ^0.1.1
  markdown: ^7.3.0
  widgetbook_documentation_addon:
    path: ../../../github/widgetbook_documentation_addon/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build: ^2.4.2
  build_runner: ^2.4.14
  widgetbook_generator: ^3.9.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/markdown/
  fonts:
    - family: Inter
      fonts:
        - asset: packages/septeo_design_system/fonts/Inter-Medium.ttf
          weight: 500
        - asset: packages/septeo_design_system/fonts/Inter-Bold.ttf
          weight: 700
