name: widgets_demo
description: "Espace de présentation des Widgets du Design System Septeo."
publish_to: 'none'
version: 0.1.1+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  widgetbook: ^3.11.0
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  url_launcher_web: ^2.4.0
  flutter_markdown: ^0.7.6+2
  intl: ^0.20.2
  septeo_design_system:
    path: ../
  widgetbook_annotation: ^3.3.0
  flutter_resizable_container: ^4.0.1
  flutter_animate: ^4.5.2
  flutter_highlighter: ^0.1.1
  markdown: ^7.3.0
  widgetbook_documentation_addon: ^1.0.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build: ^2.4.2
  build_runner: ^2.4.15
  widgetbook_generator: ^3.10.0

flutter:

  assets:
    - assets/
    - assets/images/
    - assets/markdown/
    - assets/markdown/dss-foundations/
    - assets/markdown/dss-foundations/textstyles/
    - assets/markdown/dss-foundations/colorscale/
    - assets/markdown/dss-components/
    - assets/markdown/dss-components/form/
    - assets/markdown/dss-components/form/dssbutton/
    - assets/markdown/dss-components/form/radioselector/
    - assets/markdown/dss-components/form/optionswitch/
    - assets/markdown/dss-components/form/textdynamicinput/
  uses-material-design: true
