name: widgets_demo
description: "Espace de présentation des Widgets du Design System Septeo."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  widgetbook: ^3.9.0
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  url_launcher_web: ^2.3.3
  flutter_markdown: ^0.7.4
  intl: ^0.19.0
  septeo_design_system:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/markdown/
  fonts:
    - family: Inter
      fonts:
        - asset: packages/septeo_design_system/fonts/Inter-Regular.ttf
          weight: 400
        - asset: packages/septeo_design_system/fonts/Inter-Medium.ttf
          weight: 500
        - asset: packages/septeo_design_system/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: packages/septeo_design_system/fonts/Inter-Bold.ttf
          weight: 700
        - asset: packages/septeo_design_system/fonts/Inter-ExtraBold.ttf
          weight: 800
